services:
  nginx:
    image: tiangolo/nginx-rtmp:latest-2024-06-17
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - streams:/hls/live
    ports:
      - "1935:1935"
    depends_on:
      - stream_auth

  stream_auth:
    hostname: stream_auth
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - streams:/hls/live
    ports:
      - "8080:8080"

volumes:
  streams:

networks:
  default:
    name: streaming-server
